apiVersion: v1
kind: Namespace
metadata:
  name: frontend-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend-secret
          image: cgamel/p7-frontend:13b3b739
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: NEXT_PUBLIC_API_BASE_URL
            - name: NEXT_PUBLIC_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: NEXT_PUBLIC_BASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment-service
  namespace: frontend-deployment
spec:
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-deployment-ingress
  namespace: frontend-deployment
spec:
  rules:
    - host: frontend-deployment.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-deployment-service
                port:
                    number: 3000  # Expose through the service port (3000)
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-deployment-hpa
  namespace: frontend-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Trigger scaling if CPU usage exceeds 70%
