apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:P7-Chaos-Academy/devops.git
    targetRevision: main
    path: strato-api 
  destination:
    server: https://kubernetes.default.svc
    namespace: strato-api 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true