apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strato-api
  namespace: strato-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: api.gamel.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strato-api
                port:
                  number: 8080
  tls:
    - secretName: strato-api-tls
      hosts:
        - api.gamel.dk
