apiVersion: v1
kind: Namespace
metadata:
  name: cluster-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-deployment
  namespace: cluster-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-deployment
  template:
    metadata:
      labels:
        app: cluster-deployment
    spec:
      containers:
        - name: cluster-container
          image: cgamel/cluster-api:61c613bc
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-deployment-service
  namespace: cluster-namespace
spec:
  selector:
    app: cluster-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-deployment-ingress
  namespace: cluster-namespace
spec:
  rules:
    - host: cluster-deployment.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-deployment-service
                port:
                  number: 8080  # Expose through the service port (8080)
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cluster-deployment-hpa
  namespace: cluster-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cluster-deployment
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Trigger scaling if CPU usage exceeds 70%