apiVersion: v1
kind: Service
metadata:
  name: strato-api
  namespace: strato-api
spec:
  selector:
    app: strato-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
